version: '3.8'

services:
  token:
    build:
      context: ./token_service
      dockerfile: token.Dockerfile
    ports:
      - "8001:8001"
  courses:
    build:
      context: courses_service
      dockerfile: courses_service/courses.Dockerfile
    ports:
      - "8002:8002"
  teachers:
    build:
      context: teachers_service
      dockerfile: teachers_service/teachers.Dockerfile
    ports:
      - "8003:8003"
  electronic_store:
    build:
      context: e_learning
      dockerfile: e_learning/e_learn.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - token
      - courses
      - teachers